name: Build and test

on:
  push:
    paths-ignore:
    - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use nodejs:${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - name: Build docker images
      run: yarn docker:build
    - name: Run docker and test
      run: |
        yarn docker:run
    - name: Test
      run: |
        ls -la
        docker exec -i node ls -la
        yarn docker:install
        yarn docker:test
    - name: Stop docker
      run: yarn docker:rm