name: Push images

on:
  workflow_run:
    workflows: Build and test
    branches: master
    types: completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag-version:
        - 16-bullseye-slim
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        context: .
          platforms: |-
            linux/amd64
            linux/arm64
        cache-from: type=gha
        cache-to: type=gha
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: gaainf/node-ppt
        tags: ${{ matrix.tag-version }}
        build_args: VERSION=${{ matrix.tag-version }}